### ISSUE TITLE
How long do I have to wait after sending the email?

### ISSUE THREAD

**Issue by wy-luke** [Akshathakrbhat/Manipal-UAV-Person-Dataset#1]
I sent the email and filled the form as required days ago. But I did receive the reply.

So I want to konw how long do I have to wait after sending the email, or is there something wrong?

Many thanks to you and your contribution. Respect!
@Akshathakrbhat @kphanipavan

**Comment by kphanipavan** [comment]
Hi Luke,

Apologies for not responding to your request. We are a little backed up on our work. @Akshathakrbhat manages access to the dataset, and I personally contacted her regarding the same. I will let you know here as soon as she processes your request.

Thank you for showing interest in our dataset.

~Pvn

**Comment by kphanipavan** [comment]
I hope you are given access to the dataset. If so, do close this issue.

~ Pvn.

**Comment by wy-luke** [comment]
> 

Not yet. I'll close this issue if I receive the email. Thanks!

**Comment by Akshathakrbhat** [comment]
> I sent the email and filled the form as required days ago. But I did receive the reply.
> 
> So I want to konw how long do I have to wait after sending the email, or is there something wrong?
> 
> Many thanks to you and your contribution. Respect! @Akshathakrbhat @kphanipavan


We appreciate your interest in our work, and sorry for the inconvenience caused. 
We are in the process of completing the university formalities to share the dataset to the public, as the data is acquired inside our university premises.  Due to this, there is some delay in data sharing.  We will complete this as soon as possible, and it will be made available to you, possibly by June/July 2023.

**Comment by wy-luke** [comment]
@Akshathakrbhat Oops, my thesis should have been submitted by then, and the deadline is approaching.

I comprehend what you need to do, so I will try to explore other options. Thank you anyway.

**Comment by kphanipavan** [comment]
Hi,

FYI, we received the approval for providing controlled access to the dataset for research purposes. Access to the data shall be shared (to all who filled the form) by end of this month.

~Pvn
