### ISSUE TITLE
Apply for use

### ISSUE THREAD

**Issue by baowenshuwh** [Akshathakrbhat/Manipal-UAV-Person-Dataset#2]
Hello, I hope to use your pedestrian detection data set from the UAV perspective in my paper. I think it is a good UAV small target detection dataSet. I applied for the data set in the way you provided, but I did not receive any reply.

**Comment by kphanipavan** [comment]
Hello @baowenshuwh 

Please refer #1 for an explanation.

TL;DR 
Need clearance, maybe done by july this year.

Thank you, Regards.

~Pvn

**Comment by kphanipavan** [comment]
https://github.com/Akshathakrbhat/Manipal-UAV-Person-Dataset/issues/1#issuecomment-1647727542

~Pvn

**Comment by Zyr181yeah** [comment]
Hello, I hope to use your pedestrian detection data set from the UAV perspective in my paper. I think it is a good UAV small target detection dataSet. I applied for the data set in the way you provided, but I did not receive any reply.

**Comment by Zyr181yeah** [comment]
> Hello, I hope to use your pedestrian detection data set from the UAV perspective in my paper. I think it is a good UAV small target detection dataSet. I applied for the data set in the way you provided, but I did not receive any reply.

Hello, have you received this data set? I applied for it but got no reply. Could you please use yours? Thank you!

**Comment by Akshathakrbhat** [comment]
The dataset link has been shared long back. If not kindly mail to : akshatha.kr@manipal.edu. The access will be given to you.
