### ISSUE TITLE
Accept Dataset

### ISSUE THREAD

**Issue by trongthanhqvo** [Akshathakrbhat/Manipal-UAV-Person-Dataset#3]
Hi @kphanipavan,

With the desire to use that dataset, I sent a request via the form.
Could you consider accepting access to the dataset for me soon? 
email: thanhlio3625328@gmail.com

Thanks!

**Comment by Akshathakrbhat** [comment]
> Hi @kphanipavan,
> 
> With the desire to use that dataset, I sent a request via the form. Could you consider accepting access to the dataset for me soon? email: [thanhlio3625328@gmail.com](mailto:thanhlio3625328@gmail.com)
> 
> Thanks!

The access link has been shared already. Please check. If not, please send mail to: akshatha.kr@manipal.edu
